version: "3.7"

services:
  db:
    build: ./db
    container_name: albums_db
    ports:
      - "1433:1433"

  api:
    build:
      context: ./api/src/albums
      dockerfile: Dockerfile
    container_name: albums_api
    ports:
      - "5000:80"
    depends_on:
      - db

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: albums_ui
    ports:
      - "3000:3000"
    depends_on:
      - api
